### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by rmast** [zzd1992/Numpy-Pytorch-Bicubic#2]
Program:
```
from pyResize import DownSample, UpSample, imresize
import torch
import torchvision
from torchvision.io import read_image, write_png
img = read_image("/home/rmast/175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36.jpg")
up = UpSample(4)
groter = up(img)
write_png(groter,"/home/rmast/erggroot.png")
```
https://user-images.githubusercontent.com/3341558/175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36.jpg

```
Traceback (most recent call last):
  File "doe.py", line 7, in <module>
    groter = up(img)
  File "/home/rmast/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rmast/Numpy-Pytorch-Bicubic/pyResize/resize_torch.py", line 85, in forward
    b, c, h, w = x.size()
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by zzd1992** [comment]
You should check the shape of `img`.
For a single image, we expect its shape is `(1, c, h, w)`.
